esphome:
  name: ESPHome-sofarg3
  friendly_name: ESPHome SofarG3

esp32:
  #board: esp32-c3-devkitm-1
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:
  #baud_rate: 0

# Enable Home Assistant API
api:

ota:
 

wifi:
  ssid: !secret George
  password: !secret wifi_password


uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 19200
  stop_bits: 2
  parity: NONE
  

modbus:
  flow_control_pin: 5
  id: modbus1
  

modbus_controller:
  - id: ecoModbus
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 15s
    command_throttle: 100ms

sensor: 
  - platform: modbus_controller
    modbus_controller_id: ecoModbus
    name: "pv_1_power",
		register: "0x0586",
		function: "multiply",
		factor: 10,
			ha:
				device_class: "power",
				unit_of_measurement: "W",
				name: "PV1 Power",
				icon: "mdi:solar-power",
				state_class: "measurement",
				entity_category: "diagnostic",
				value_template: "{{ value_json.pv_1_power }}"
  
  -platform: modbus_controller
    modbus_controller_id: ecoModbus
    name: "pv_2_power",
		register: "0x0589",
		function": "multiply",
		factor": 10,
		  ha:
				device_class: "power",
				unit_of_measurement: "W",
				name: "PV2 Power",
				icon: "mdi:solar-power",
				state_class: "measurement",
				entity_category: "diagnostic",
				value_template: "{{ value_json.pv_2_power }}"